#ifndef GUARD_CONSTANTS_LETTERS_H
#define GUARD_CONSTANTS_LETTERS_H

#define LETTER_RIDDLE_ENCODED       0
#define LETTER_RIDDLE_DECODED       1
#define LETTER_MEL_MIKE_ENCODED     2
#define LETTER_MEL_MIKE_DECODED     3
#define LETTER_TY_ALEX_ENCODED      4
#define LETTER_TY_ALEX_DECODED      5
#define LETTER_MARY_ARIC_ENCODED    6
#define LETTER_MARY_ARIC_DECODED    7
#define LETTER_MOM_DAD_ENCODED      8
#define LETTER_MOM_DAD_DECODED      9
#define LETTER_BRO_SIS_ENCODED      10
#define LETTER_BRO_SIS_DECODED      11
#define LETTER_CHRIS_ENCODED        12
#define LETTER_CHRIS_DECODED        13

#endif